import UnicoProofs.Platonici.PassoInduttivo

open Set
open scoped RealInnerProductSpace

noncomputable section

namespace LeanEval.Geometry.PlatonicClassification

open ConvexPolytope FiniteConvexPolytope Module

/-- Every face of a convex polytope is contained in a supporting level set,
and the whole polytope lies in the corresponding closed half-space. -/
theorem corpo_da_una_parte (P : ConvexPolytope 3)
    {F : Set (E 3)} (hF : P.IsFace F) :
    ∃ l : E 3 →L[Real] Real, ∃ c : Real,
      (∀ z ∈ P.toSet, l z ≤ c) ∧ (∀ z ∈ F, l z = c) := by
  obtain ⟨y, hy⟩ := hF.2
  obtain ⟨l, hmax, _⟩ := espositore_di_faccia P hF
  refine ⟨l, l y, hmax y hy |>.2, ?_⟩
  intro z hz
  exact le_antisymm (hmax y hy |>.2 z (hmax z hz).1)
    (hmax z hz |>.2 y (hmax y hy).1)

/-- The supporting inequality is strict at every point of the polytope
outside the exposed face. -/
theorem corpo_da_una_parte_stretto (P : ConvexPolytope 3)
    {F : Set (E 3)} (hF : P.IsFace F) :
    ∃ l : E 3 →L[Real] Real, ∃ c : Real,
      (∀ z ∈ P.toSet, l z ≤ c) ∧ (∀ z ∈ F, l z = c) ∧
      (∀ z ∈ P.toSet, z ∉ F → l z < c) := by
  obtain ⟨y, hy⟩ := hF.2
  obtain ⟨l, hmax, hchar⟩ := espositore_di_faccia P hF
  refine ⟨l, l y, hmax y hy |>.2, ?_, ?_⟩
  · intro z hz
    exact le_antisymm (hmax y hy |>.2 z (hmax z hz).1)
      (hmax z hz |>.2 y (hmax y hy).1)
  · intro z hzP hzF
    have hle : l z ≤ l y := (hmax y hy).2 z hzP
    exact lt_of_le_of_ne hle fun heq => hzF (hchar z hzP fun x hxP =>
      (hmax y hy).2 x hxP |>.trans (le_of_eq heq.symm))

/-- A direction from a point of a supporting face towards a point strictly
below its supporting level has negative functional value. -/
theorem direzione_negativa_da_supporto
    {v x : E 3} {l : E 3 →L[Real] Real} {c : Real}
    (hv : l v = c) (hx : l x < c) (hvx : x ≠ v) :
    l (‖x - v‖⁻¹ • (x - v)) < 0 := by
  rw [map_smul, map_sub, smul_eq_mul]
  exact mul_neg_of_pos_of_neg
    (inv_pos.mpr (norm_pos_iff.mpr (sub_ne_zero.mpr hvx))) (by linarith)

/-- Linearity of the mixed volume in its last argument under scalar
multiplication. -/
theorem volumeTre_smul (u r z : E 3) (a : Real) :
    volumeTre u r (a • z) = a * volumeTre u r z := by
  let f := orientazioneTre.volumeForm
  have h := f.map_update_smul ![u, r, 0] (2 : Fin 3) a z
  have hsmul : Function.update ![u, r, 0] (2 : Fin 3) (a • z) =
      ![u, r, a • z] := by
    funext i
    fin_cases i <;> rfl
  have hz : Function.update ![u, r, 0] (2 : Fin 3) z = ![u, r, z] := by
    funext i
    fin_cases i <;> rfl
  change f ![u, r, a • z] = a * f ![u, r, z]
  simpa only [hsmul, hz, smul_eq_mul] using h

/-- Two vectors on the same strict side of the plane generated by two
independent vectors give mixed volumes with the same sign. -/
theorem segno_volume_da_lato
    {u r z z' : E 3} {l : E 3 →L[Real] Real}
    (hpiano_u : l u = 0) (hpiano_r : l r = 0)
    (hz : l z < 0) (hz' : l z' < 0)
    (hind : LinearIndependent Real ![u, r]) :
    0 < volumeTre u r z * volumeTre u r z' := by
  let t : Fin 3 → E 3 := ![u, r, z]
  have ht : LinearIndependent Real t := by
    rw [Fintype.linearIndependent_iff]
    intro g hsum i
    have hlsum := congrArg l hsum
    have hg2 : g 2 = 0 := by
      have hcoef : g 2 * l z = 0 := by
        simpa [t, Fin.sum_univ_three, hpiano_u, hpiano_r, smul_eq_mul]
          using hlsum
      exact (mul_eq_zero.mp hcoef).resolve_right (ne_of_lt hz)
    have hpair : ∑ j : Fin 2, g j.castSucc • ![u, r] j = 0 := by
      simpa [t, Fin.sum_univ_three, Fin.sum_univ_two, hg2] using hsum
    have hzero := Fintype.linearIndependent_iff.mp hind
      (fun j : Fin 2 => g j.castSucc) hpair
    fin_cases i
    · exact hzero 0
    · exact hzero 1
    · exact hg2
  have hcard : Fintype.card (Fin 3) = Module.finrank Real (E 3) := by
    rw [Fintype.card_fin, finrank_euclideanSpace_fin]
  let B : Basis (Fin 3) Real (E 3) :=
    basisOfLinearIndependentOfCardEqFinrank ht hcard
  let a : Real := B.repr z' 0
  let b : Real := B.repr z' 1
  let d : Real := B.repr z' 2
  have hdecomp : z' = a • u + b • r + d • z := by
    rw [← B.sum_repr z']
    simp [B, t, a, b, d, Fin.sum_univ_three,
      coe_basisOfLinearIndependentOfCardEqFinrank]
  have hld : l z' = d * l z := by
    rw [hdecomp]
    simp [hpiano_u, hpiano_r, smul_eq_mul]
  have hd : 0 < d := by
    have hprod : d * l z < 0 := by rwa [← hld]
    rcases (mul_neg_iff.mp hprod) with hgood | hbad
    · exact hgood.1
    · exact (not_lt_of_ge (le_of_lt hz) hbad.2).elim
  have hvolu : volumeTre u r u = 0 := by
    exact orientazioneTre.volumeForm.map_eq_zero_of_eq ![u, r, u]
      (by rfl) (by decide : (0 : Fin 3) ≠ 2)
  have hvolr : volumeTre u r r = 0 := by
    exact orientazioneTre.volumeForm.map_eq_zero_of_eq ![u, r, r]
      (by rfl) (by decide : (1 : Fin 3) ≠ 2)
  have hvoldecomp : volumeTre u r z' = d * volumeTre u r z := by
    have h := congrArg (fun x => volumeTre u r x) hdecomp
    simpa only [volumeTre_add, volumeTre_smul, hvolu, hvolr, mul_zero,
      zero_add] using h
  have hform : orientazioneTre.volumeForm ≠ 0 := by
    let O := orientazioneTre.finOrthonormalBasis
      (by norm_num : 0 < 3) (Fact.out : Module.finrank Real (E 3) = 3)
    rw [orientazioneTre.volumeForm_robust O
      (orientazioneTre.finOrthonormalBasis_orientation
        (by norm_num : 0 < 3) (Fact.out : Module.finrank Real (E 3) = 3))]
    exact O.toBasis.det_ne_zero
  have hvolz : volumeTre u r z ≠ 0 := by
    have hB := (orientazioneTre.volumeForm.map_basis_ne_zero_iff B).2 hform
    simpa only [volumeTre, B,
      coe_basisOfLinearIndependentOfCardEqFinrank] using hB
  calc
    0 < d * (volumeTre u r z) ^ 2 :=
      mul_pos hd (sq_pos_of_ne_zero hvolz)
    _ = volumeTre u r z * volumeTre u r z' := by
      rw [hvoldecomp]
      ring

/-- Local orientation discharge once the two fans at the adjacent vertex
have been aligned on the common facet.  The common old ray outside that
facet fixes the three-dimensional side for both polytopes. -/
theorem orientazione_al_vicino_allineato
    (P Q : ConvexPolytope 3) {p q : Nat} [NeZero q]
    (hP : P.asFinite.IsCyclicallyRegularOfType p q)
    (_hQ : Q.asFinite.IsCyclicallyRegularOfType p q)
    (hq : 3 ≤ q) {v w : E 3}
    (hwP : w ∈ P.vertices) (_hwQ : w ∈ Q.vertices)
    (DP : P.asFinite.CyclicVertexData v q)
    (DQ : Q.asFinite.CyclicVertexData v q)
    (EP : P.asFinite.CyclicVertexData w q)
    (EQ : Q.asFinite.CyclicVertexData w q)
    (hdir : dir P.asFinite v DP = dir Q.asFinite v DQ)
    (i : Fin q)
    (hEP1 : EP.faccetta 1 = DP.faccetta i)
    (hEQ1 : EQ.faccetta 1 = DQ.faccetta i)
    (hzero : dir P.asFinite w EP 0 = dir Q.asFinite w EQ 0)
    (huno : dir P.asFinite w EP 1 = dir Q.asFinite w EQ 1)
    (k : Fin q) (hk0 : k ≠ 0) (hk1 : k ≠ 1) :
    0 < volumeTre (dir P.asFinite w EP 0) (dir P.asFinite w EP 1)
          (dir P.asFinite w EP k) *
        volumeTre (dir Q.asFinite w EQ 0) (dir Q.asFinite w EQ 1)
          (dir Q.asFinite w EQ k) := by
  classical
  have hrot01 : finRotate q (0 : Fin q) = 1 := by
    simp [finRotate_apply]
  let sidx : Fin q := finRotate q i
  have hsidx_ne : sidx ≠ i := by
    exact _root_.finRotate_ne_self (by omega : 2 ≤ q) i
  have hsidx2_ne : finRotate q sidx ≠ i := by
    simpa only [sidx] using finRotate_due_ne hq i
  have hrotk_ne : finRotate q k ≠ 1 := by
    intro hk
    apply hk0
    exact (finRotate q).injective (hk.trans hrot01.symm)
  have hfaceP : P.IsFace (DP.faccetta i) :=
    ((P.asFinite_isFacet_iff (DP.faccetta i)).1 (DP.isFacet i)).1
  have hfaceQ : Q.IsFace (DQ.faccetta i) :=
    ((Q.asFinite_isFacet_iff (DQ.faccetta i)).1 (DQ.isFacet i)).1
  obtain ⟨lP, cP, hbodyP, hlevelP, hstrictP⟩ :=
    corpo_da_una_parte_stretto P hfaceP
  obtain ⟨lQ, cQ, hbodyQ, hlevelQ, hstrictQ⟩ :=
    corpo_da_una_parte_stretto Q hfaceQ
  have hvFP : v ∈ DP.faccetta i := DP.mem_v i
  have hvFQ : v ∈ DQ.faccetta i := DQ.mem_v i
  have hwFP : w ∈ DP.faccetta i := by
    rw [← hEP1]
    exact EP.mem_v 1
  have hwFQ : w ∈ DQ.faccetta i := by
    rw [← hEQ1]
    exact EQ.mem_v 1
  have hsoutP : punto P.asFinite v DP sidx ∉ DP.faccetta i := by
    intro hsF
    have hs := punto_spec P.asFinite v DP sidx
    rcases DP.spigolo_due sidx i (punto P.asFinite v DP sidx)
        hs.2 hs.1 hsF with hi | hi
    · exact hsidx_ne hi.symm
    · exact hsidx2_ne hi.symm
  have hsoutQ : punto Q.asFinite v DQ sidx ∉ DQ.faccetta i := by
    intro hsF
    have hs := punto_spec Q.asFinite v DQ sidx
    rcases DQ.spigolo_due sidx i (punto Q.asFinite v DQ sidx)
        hs.2 hs.1 hsF with hi | hi
    · exact hsidx_ne hi.symm
    · exact hsidx2_ne hi.symm
  have hkoutP : punto P.asFinite w EP k ∉ DP.faccetta i := by
    intro hkF
    have hs := punto_spec P.asFinite w EP k
    have hkF' : punto P.asFinite w EP k ∈ EP.faccetta 1 := by
      rwa [hEP1]
    rcases EP.spigolo_due k 1 (punto P.asFinite w EP k)
        hs.2 hs.1 hkF' with h | h
    · exact hk1 h.symm
    · exact hrotk_ne h.symm
  have hkoutQ : punto Q.asFinite w EQ k ∉ DQ.faccetta i := by
    intro hkF
    have hs := punto_spec Q.asFinite w EQ k
    have hkF' : punto Q.asFinite w EQ k ∈ EQ.faccetta 1 := by
      rwa [hEQ1]
    rcases EQ.spigolo_due k 1 (punto Q.asFinite w EQ k)
        hs.2 hs.1 hkF' with h | h
    · exact hk1 h.symm
    · exact hrotk_ne h.symm
  have hsbodyP : punto P.asFinite v DP sidx ∈ P.toSet :=
    (DP.isFacet sidx).1.1.subset (punto_spec P.asFinite v DP sidx).2.1
  have hsbodyQ : punto Q.asFinite v DQ sidx ∈ Q.toSet :=
    (DQ.isFacet sidx).1.1.subset (punto_spec Q.asFinite v DQ sidx).2.1
  have hkbodyP : punto P.asFinite w EP k ∈ P.toSet :=
    (EP.isFacet k).1.1.subset (punto_spec P.asFinite w EP k).2.1
  have hkbodyQ : punto Q.asFinite w EQ k ∈ Q.toSet :=
    (EQ.isFacet k).1.1.subset (punto_spec Q.asFinite w EQ k).2.1
  have hlPs : lP (dir P.asFinite v DP sidx) < 0 := by
    exact direzione_negativa_da_supporto (hlevelP v hvFP)
      (hstrictP _ hsbodyP hsoutP) (punto_spec P.asFinite v DP sidx).1
  have hlQs : lQ (dir Q.asFinite v DQ sidx) < 0 := by
    exact direzione_negativa_da_supporto (hlevelQ v hvFQ)
      (hstrictQ _ hsbodyQ hsoutQ) (punto_spec Q.asFinite v DQ sidx).1
  have hlPk : lP (dir P.asFinite w EP k) < 0 := by
    exact direzione_negativa_da_supporto (hlevelP w hwFP)
      (hstrictP _ hkbodyP hkoutP) (punto_spec P.asFinite w EP k).1
  have hlQk : lQ (dir Q.asFinite w EQ k) < 0 := by
    exact direzione_negativa_da_supporto (hlevelQ w hwFQ)
      (hstrictQ _ hkbodyQ hkoutQ) (punto_spec Q.asFinite w EQ k).1
  have hp0P : punto P.asFinite w EP 0 ∈ DP.faccetta i := by
    have hmem := (punto_spec P.asFinite w EP 0).2.2
    simpa only [hrot01, hEP1] using hmem
  have hp1P : punto P.asFinite w EP 1 ∈ DP.faccetta i := by
    simpa only [hEP1] using (punto_spec P.asFinite w EP 1).2.1
  have hp0Q : punto Q.asFinite w EQ 0 ∈ DQ.faccetta i := by
    have hmem := (punto_spec Q.asFinite w EQ 0).2.2
    simpa only [hrot01, hEQ1] using hmem
  have hp1Q : punto Q.asFinite w EQ 1 ∈ DQ.faccetta i := by
    simpa only [hEQ1] using (punto_spec Q.asFinite w EQ 1).2.1
  have hlP0 : lP (dir P.asFinite w EP 0) = 0 := by
    simp [dir, map_sub, hlevelP _ hp0P, hlevelP w hwFP, smul_eq_mul]
  have hlP1 : lP (dir P.asFinite w EP 1) = 0 := by
    simp [dir, map_sub, hlevelP _ hp1P, hlevelP w hwFP, smul_eq_mul]
  have hlQ0 : lQ (dir Q.asFinite w EQ 0) = 0 := by
    simp [dir, map_sub, hlevelQ _ hp0Q, hlevelQ w hwFQ, smul_eq_mul]
  have hlQ1 : lQ (dir Q.asFinite w EQ 1) = 0 := by
    simp [dir, map_sub, hlevelQ _ hp1Q, hlevelQ w hwFQ, smul_eq_mul]
  have hindP : LinearIndependent Real
      ![dir P.asFinite w EP 0, dir P.asFinite w EP 1] := by
    simpa only [hrot01] using
      raggi_consecutivi_indipendenti P hP hwP EP (0 : Fin q)
  have hindQ : LinearIndependent Real
      ![dir Q.asFinite w EQ 0, dir Q.asFinite w EQ 1] := by
    simpa only [← hzero, ← huno] using hindP
  have hsideP := segno_volume_da_lato hlP0 hlP1 hlPk hlPs hindP
  have hsideQ := segno_volume_da_lato hlQ0 hlQ1 hlQk hlQs hindQ
  have hsdir : dir P.asFinite v DP sidx = dir Q.asFinite v DQ sidx :=
    congrFun hdir sidx
  have hsideQ' :
      0 < volumeTre (dir P.asFinite w EP 0) (dir P.asFinite w EP 1)
            (dir Q.asFinite w EQ k) *
          volumeTre (dir P.asFinite w EP 0) (dir P.asFinite w EP 1)
            (dir P.asFinite v DP sidx) := by
    simpa only [← hzero, ← huno, ← hsdir] using hsideQ
  rcases (mul_pos_iff.mp hsideP) with ⟨hPk, hPs⟩ | ⟨hPk, hPs⟩
  · rcases (mul_pos_iff.mp hsideQ') with ⟨hQk, _⟩ | ⟨_, hQs⟩
    · simpa only [← hzero, ← huno] using mul_pos hPk hQk
    · exact (not_lt_of_ge (le_of_lt hPs) hQs).elim
  · rcases (mul_pos_iff.mp hsideQ') with ⟨_, hQs⟩ | ⟨hQk, _⟩
    · exact (not_lt_of_ge (le_of_lt hQs) hPs).elim
    · simpa only [← hzero, ← huno] using mul_pos_of_neg_of_neg hPk hQk

/-- The inductive step with the orientation condition discharged from the
supporting half-spaces of the aligned common facet. -/
theorem ventagli_uguali_al_vicino_scarico
    (P Q : ConvexPolytope 3) {p q : Nat} [NeZero q]
    (hP : P.asFinite.IsCyclicallyRegularOfType p q)
    (hQ : Q.asFinite.IsCyclicallyRegularOfType p q)
    {v : E 3} (hvP : v ∈ P.vertices) (hvQ : v ∈ Q.vertices)
    (DP : P.asFinite.CyclicVertexData v q)
    (DQ : Q.asFinite.CyclicVertexData v q)
    (hdir : dir P.asFinite v DP = dir Q.asFinite v DQ)
    (hdiam : ∀ k, Metric.diam
        (DP.faccetta k ∩ DP.faccetta (finRotate q k)) =
      Metric.diam (DQ.faccetta k ∩ DQ.faccetta (finRotate q k)))
    (i : Fin q) :
    ∃ (w : E 3) (_hwP : w ∈ P.vertices) (_hwQ : w ∈ Q.vertices)
      (EP : P.asFinite.CyclicVertexData w q)
      (EQ : Q.asFinite.CyclicVertexData w q),
      dir P.asFinite w EP = dir Q.asFinite w EQ := by
  classical
  have hq : 3 ≤ q := hP.2.2.1
  obtain ⟨w, hwP, hwQ, hwne, hwEdgeP, hsegP, hedge⟩ :=
    vertice_adiacente_comune P Q hP hQ hvP hvQ DP DQ hdir hdiam i
  have hwEdgeQ : w ∈ DQ.faccetta i ∩ DQ.faccetta (finRotate q i) := by
    rw [← hedge]
    exact hwEdgeP
  have hsegQ : DQ.faccetta i ∩ DQ.faccetta (finRotate q i) =
      segment Real v w := hedge.symm.trans hsegP
  have hfaceEdgeP := adiacenza_passo_uno_locale P hq DP i
  have hfaceEdgeQ := adiacenza_passo_uno_locale Q hQ.2.2.1 DQ i
  have hfacetNeP : DP.faccetta (finRotate q i) ≠ DP.faccetta i := by
    intro h
    apply _root_.finRotate_ne_self (by omega : 2 ≤ q) i
    exact DP.distinte h
  have hfacetNeQ : DQ.faccetta (finRotate q i) ≠ DQ.faccetta i := by
    intro h
    apply _root_.finRotate_ne_self (by omega : 2 ≤ q) i
    exact DQ.distinte h
  obtain ⟨EP, hEP0, hEP1⟩ := fan_allineato_su_faccette P hP hwP
    (Ne.symm hwne) (DP.isFacet (finRotate q i)) (DP.isFacet i) hfacetNeP
    hwEdgeP.2 hwEdgeP.1 (DP.mem_v (finRotate q i)) (DP.mem_v i)
    hfaceEdgeP.1 hfaceEdgeP.2.1 hwEdgeP
    ⟨DP.mem_v i, DP.mem_v (finRotate q i)⟩
    Set.inter_subset_right Set.inter_subset_left
  obtain ⟨EQ, hEQ0, hEQ1⟩ := fan_allineato_su_faccette Q hQ hwQ
    (Ne.symm hwne) (DQ.isFacet (finRotate q i)) (DQ.isFacet i) hfacetNeQ
    hwEdgeQ.2 hwEdgeQ.1 (DQ.mem_v (finRotate q i)) (DQ.mem_v i)
    hfaceEdgeQ.1 hfaceEdgeQ.2.1 hwEdgeQ
    ⟨DQ.mem_v i, DQ.mem_v (finRotate q i)⟩
    Set.inter_subset_right Set.inter_subset_left
  have hrot01 : finRotate q (0 : Fin q) = 1 := by
    simp [finRotate_apply]
  have hedgeEP : EP.faccetta 0 ∩ EP.faccetta (finRotate q 0) =
      segment Real v w := by
    simpa only [hrot01, hEP0, hEP1, Set.inter_comm] using hsegP
  have hedgeEQ : EQ.faccetta 0 ∩ EQ.faccetta (finRotate q 0) =
      segment Real v w := by
    simpa only [hrot01, hEQ0, hEQ1, Set.inter_comm] using hsegQ
  have huPform := direzione_su_segmento_noto P hP hwP hvP
    (Ne.symm hwne) EP 0 hedgeEP
  have huQform := direzione_su_segmento_noto Q hQ hwQ hvQ
    (Ne.symm hwne) EQ 0 hedgeEQ
  have hzero : dir P.asFinite w EP 0 = dir Q.asFinite w EQ 0 := by
    rw [huPform, huQform]
  let j : Fin q := (finRotate q).symm i
  have hji : finRotate q j = i := (finRotate q).apply_symm_apply i
  let u : E 3 := dir P.asFinite w EP 0
  let r : E 3 := dir P.asFinite v DP j
  let z : E 3 := dir P.asFinite w EP 1
  let z' : E 3 := dir Q.asFinite w EQ 1
  have hOldForm := direzione_su_segmento_noto P hP hvP hwP hwne DP i
    (by simpa only [segment_symm] using hsegP)
  have huOld : u = -dir P.asFinite v DP i := by
    rw [show u = dir P.asFinite w EP 0 by rfl, huPform, hOldForm]
    have hsub : v - w = -(w - v) := by abel
    rw [hsub, norm_neg, smul_neg]
  have hcons : LinearIndependent Real
      ![r, dir P.asFinite v DP i] := by
    simpa only [r, hji] using raggi_consecutivi_indipendenti P hP hvP DP j
  have hconsSwap : LinearIndependent Real
      ![dir P.asFinite v DP i, r] := LinearIndependent.pair_symm_iff.mp hcons
  have hscaled := indipendenti_smul_separati
    (by norm_num : (-1 : Real) ≠ 0) (by norm_num : (1 : Real) ≠ 0) hconsSwap
  have hind : LinearIndependent Real ![u, r] := by
    have hminus : (-1 : Real) • dir P.asFinite v DP i = u := by
      rw [neg_one_smul, ← huOld]
    simpa only [hminus, one_smul] using hscaled
  obtain ⟨wData, hsegDataP, _, hpiano, hsemi⟩ :=
    dati_faccetta_adiacente P Q hP hQ hvP hvQ DP DQ hdir hdiam i
  have hwData : wData = w := by
    exact (secondo_estremo_segmento_unico (Ne.symm hwne)
      (hsegP.symm.trans hsegDataP)).symm
  subst wData
  rcases hsemi with ⟨phi, hphiEdge, hlowerP, hlowerQ, hlevelP, hlevelQ⟩
  have hphiu : phi u = 0 := by
    rw [show u = dir P.asFinite w EP 0 by rfl, huPform]
    simp [map_sub, smul_eq_mul, hphiEdge]
  have hjne : j ≠ i := by
    intro hj
    apply _root_.finRotate_ne_self (by omega : 2 ≤ q) i
    simpa only [hj] using hji
  have hjneNext : j ≠ finRotate q i := by
    intro hj
    apply finRotate_due_ne hq i
    calc
      finRotate q (finRotate q i) = finRotate q j := by rw [hj]
      _ = i := hji
  have hpointR : punto P.asFinite v DP j ∈ DP.faccetta i := by
    simpa only [hji] using (punto_spec P.asFinite v DP j).2.2
  have hlevelOld : {y ∈ DP.faccetta i | phi y = phi v} =
      DP.faccetta i ∩ DP.faccetta (finRotate q i) :=
    hlevelP.trans hsegP.symm
  have hphir : 0 < phi r := by
    exact funzionale_positivo_su_dir DP i j j phi (DP.mem_v i) hpointR
      (punto_spec P.asFinite v DP j).2.1 hlowerP hlevelOld hjne hjneNext
  have hrot1ne0 : finRotate q (1 : Fin q) ≠ 0 := by
    intro h
    apply finRotate_due_ne hq (0 : Fin q)
    simpa only [hrot01] using h
  have hrot1ne1 : finRotate q (1 : Fin q) ≠ 1 :=
    _root_.finRotate_ne_self (by omega : 2 ≤ q) 1
  have hlevelEP : {y ∈ DP.faccetta i | phi y = phi v} =
      EP.faccetta 0 ∩ EP.faccetta (finRotate q 0) :=
    hlevelP.trans hedgeEP.symm
  have hlevelEPw : {y ∈ DP.faccetta i | phi y = phi w} =
      EP.faccetta 0 ∩ EP.faccetta (finRotate q 0) := by
    simpa only [← hphiEdge] using hlevelEP
  have hpointZ : punto P.asFinite w EP 1 ∈ DP.faccetta i := by
    simpa only [hEP1] using (punto_spec P.asFinite w EP 1).2.1
  have hphiz : 0 < phi z := by
    exact funzionale_positivo_su_dir EP 0 1 (finRotate q 1) phi
      (by simpa only [hEP1] using EP.mem_v 1) hpointZ
      (punto_spec P.asFinite w EP 1).2.2
      (by simpa only [hEP1, ← hphiEdge] using hlowerP) hlevelEPw hrot1ne0
      (by simpa only [hrot01] using hrot1ne1)
  have hlevelEQ : {y ∈ DQ.faccetta i | phi y = phi v} =
      EQ.faccetta 0 ∩ EQ.faccetta (finRotate q 0) :=
    hlevelQ.trans hedgeEQ.symm
  have hlevelEQw : {y ∈ DQ.faccetta i | phi y = phi w} =
      EQ.faccetta 0 ∩ EQ.faccetta (finRotate q 0) := by
    simpa only [← hphiEdge] using hlevelEQ
  have hpointZ' : punto Q.asFinite w EQ 1 ∈ DQ.faccetta i := by
    simpa only [hEQ1] using (punto_spec Q.asFinite w EQ 1).2.1
  have hphiz' : 0 < phi z' := by
    exact funzionale_positivo_su_dir EQ 0 1 (finRotate q 1) phi
      (by simpa only [hEQ1] using EQ.mem_v 1) hpointZ'
      (punto_spec Q.asFinite w EQ 1).2.2
      (by simpa only [hEQ1, ← hphiEdge] using hlowerQ) hlevelEQw hrot1ne0
      (by simpa only [hrot01] using hrot1ne1)
  have huSpan : u ∈ vectorSpan Real (DP.faccetta i) := by
    have hmem := dir_mem_vectorSpan_faccetta_destra EP (0 : Fin q)
    simpa only [u, hrot01, hEP1] using hmem
  have hrSpan : r ∈ vectorSpan Real (DP.faccetta i) := by
    have hmem := dir_mem_vectorSpan_faccetta_destra DP j
    simpa only [r, hji] using hmem
  have hspanP : vectorSpan Real (DP.faccetta i) =
      Submodule.span Real ({u, r} : Set (E 3)) :=
    vectorSpan_eq_span_vettori huSpan hrSpan hind (DP.isFacet i).2
  have hzVec : z ∈ vectorSpan Real (DP.faccetta i) := by
    have hmem := dir_mem_vectorSpan_faccetta_sinistra EP (1 : Fin q)
    simpa only [z, hEP1] using hmem
  have hzVec' : z' ∈ vectorSpan Real (DQ.faccetta i) := by
    have hmem := dir_mem_vectorSpan_faccetta_sinistra EQ (1 : Fin q)
    simpa only [z', hEQ1] using hmem
  have hvectorPlane : vectorSpan Real (DP.faccetta i) =
      vectorSpan Real (DQ.faccetta i) := by
    have hdirection := congrArg AffineSubspace.direction hpiano
    simpa only [direction_affineSpan] using hdirection
  have hzSpan : z ∈ Submodule.span Real ({u, r} : Set (E 3)) := by
    rw [← hspanP]
    exact hzVec
  have hzSpan' : z' ∈ Submodule.span Real ({u, r} : Set (E 3)) := by
    rw [← hspanP, hvectorPlane]
    exact hzVec'
  have hangP := inner_direzioni_consecutive P.asFinite hP hwP EP (0 : Fin q)
  have hangQ := inner_direzioni_consecutive Q.asFinite hQ hwQ EQ (0 : Fin q)
  have hang : ⟪u, z⟫ = ⟪u, z'⟫ := by
    calc
      ⟪u, z⟫ = cosFacciale p := by simpa only [u, z, hrot01] using hangP
      _ = ⟪dir Q.asFinite w EQ 0, z'⟫ := by
        simpa only [z', hrot01] using hangQ.symm
      _ = ⟪u, z'⟫ := by simp only [u, hzero]
  have huno : z = z' := raggio_unico_da_semipiano_lineare
    (dir_unitaria P.asFinite w EP 0)
    (dir_unitaria P.asFinite w EP 1)
    (dir_unitaria Q.asFinite w EQ 1) hind phi hphiu hphir hphiz hphiz'
    hzSpan hzSpan' hang
  have hstesso : ∀ k, k ≠ 0 → k ≠ 1 →
      0 < volumeTre (dir P.asFinite w EP 0) (dir P.asFinite w EP 1)
            (dir P.asFinite w EP k) *
          volumeTre (dir Q.asFinite w EQ 0) (dir Q.asFinite w EQ 1)
            (dir Q.asFinite w EQ k) := by
    intro k hk0 hk1
    exact orientazione_al_vicino_allineato P Q hP hQ hq hwP hwQ
      DP DQ EP EQ hdir i hEP1 hEQ1 hzero huno k hk0 hk1
  have hfan := fan_geometrico_marcato_unico P Q hP hQ hwP hwQ EP EQ
    hzero huno hstesso
  exact ⟨w, hwP, hwQ, EP, EQ, hfan⟩

end LeanEval.Geometry.PlatonicClassification
